api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes and configures the New Relic Nodejs Agent"
  homepage = "https://github.com/dpacheconr/newrelic-nodejs-paketo-buildpack"
  id = "newrelic/nodejs-agent"
  keywords = ["nodejs"]
  version = "1.0.0"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]

[metadata]
  include-files = ["README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Enable the New Relic Agent"
    name = "BP_NEW_RELIC_ENABLED"


  # To use different version NR agent, update uri and version variables accordingly
  [[metadata.dependencies]]
    id = "newrelic-nodejs"
    name = "New Relic NodeJS Agent"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://registry.npmjs.org/newrelic/-/newrelic-8.14.1.tgz"
    version = "8.14.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
